### PR TITLE
fix proc_control.is_terminated after init_logging

### PR DESCRIPTION
**Pull request by pybt**

### CODE REVIEW

**Comment by jb-alvarado** [comment]
Hi pybt, thank you for contribute to ffplayout!

Can you describe me the bug? Because this pull request will not work in general. We need a instance from the same proc_control on different places, but with your fix you create two new ones.

When something's not working correctly I believe we can fix it in another way.

**Comment by pybt** [comment]
Hi jb-alvarado

When enabled ingest mode ffplayout-engine print out this log.
```
...
[ INFO] Start ingest server, listening on: rtmp://127.0.0.1:1936/live/stream
[DEBUG] Server CMD: "ffmpeg -hide_banner -nostats -v level+error -f live_flv -listen 1 -i rtmp://127.0.0.1:1936/live/stream -filter_complex [0:v]fps=25,scale=1024:576,setdar=dar=1.778,fade=in:st=0:d=0.5[vout1];[0:a]afade=in:st=0:d=0.5[aout1] -map [vout1] -map [aout1] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982k -minrate 58982k -maxrate 58982k -bufsize 29491k -c:a s302m -strict -2 -ar 48000 -ac 2 -f mpegts -"
...
```
but when start stream to `rtmp://127.0.0.1:1936/live/stream` with command below got connection refused.
```
ffmpeg -i https://<somedomain>/live/playlist.m3u8 -flvflags no_duration_filesize -f flv  rtmp://127.0.0.1:1936/live/stream
...
[tcp @ 0x5652924e1740] Connection to tcp://127.0.0.1:1936 failed: Connection refused
[rtmp @ 0x5652922b1b80] Cannot open connection tcp://127.0.0.1:1936
rtmp://127.0.0.1:1936/live/stream: Connection refused
```
I've checked process that listen to port 1936 with `netstat -anpe | grep "1936"` not found any process listen on that port.

I found at line 43 in src/input/ingest.rs the proc_control.is_terminated is true before it spawn ingest server process.
https://github.com/ffplayout/ffplayout-engine/blob/dd8221381ad2f33b175f702b8af10703a387c5fb/src/input/ingest.rs#L43-L50

**Comment by jb-alvarado** [comment]
Ah yes, there is a problem. I think I have fix this in my repo, but had not update this repo.

If you want, you can give it a try:

https://github.com/jb-alvarado/ffplayout-engine

**Comment by pybt** [comment]
Ingest server is working now with code from your repo thank for your time.

**Pull request closed without merging**
