### PR TITLE
Cleanup dependencies

### PR DESCRIPTION
**Pull request by SebastianSpeitel**

### CODE REVIEW

**Comment by jb-alvarado** [comment]
Static-files is needed by the build.rs

**Comment by SebastianSpeitel** [comment]
It's still in the build dependencies

**Comment by jb-alvarado** [comment]
Ah ok :-), thanks.

**Comment by SebastianSpeitel** [comment]
Oh sorry for that

https://github.com/jb-alvarado/ffplayout/commit/7251a76daae8e5c6eef47b17279f825d58f7df4f

**Comment by jb-alvarado** [comment]
> Oh sorry for that
> 
No problem!

**Pull request merged**
