### PR TITLE
Add docker example & documentation 

### PR DESCRIPTION
**Pull request by 0DUDDU**
As mentioned in my issue there is the example for a Dockerfile for ffplayout with some documentation

I think it will not work for now due to #273 but the fix is also included in the PR, so don't hesitate to ping me in #273 when a new build is made with the fix to confirm it's working 😉 

Feel free to review and RC if needed 🙂

### CODE REVIEW

**Comment by jb-alvarado** [comment]
Thank you for your effort! I have only some suggestions:
1. I think in Rocky and Alma Linux Systemd is working to, see here: [Dockerfile](https://github.com/eniocarboni/docker-rockylinux-systemd) and [tutorial](https://www.how2shout.com/linux/run-almalinux-or-rocky-linux-8-docker-container-with-systemd-systemctl/). Maybe you can approve this?
2. Maybe not all libs for ffmpeg is need, then it makes it more fast to build. Like libbluray and libvidstab. When you take a newer image than you could also use some libs from system, like [here](https://github.com/ffplayout/ffplayout-docker/blob/master/ffplayout-engine/Dockerfile).
3. Do you think a docker compose file will work to? I'm not so a docker pro.
4. Maybe is worth to note, that there will be a "[PIGGYBACK_MODE](https://github.com/ffplayout/ffplayout/tree/v0.17.0/ffplayout-api#piggyback-mode)"? But I would trust more the systemd solution.

**Comment by 0DUDDU** [comment]
1.  I was not aware of  Rocky and Alma Linux, I will take a look
2. Yes, I was using all libs provided by `jrottenberg/ffmpeg` but it's better if I select only the mandatory one for ffplayout
3. Yes, if it works with docker run it can run with compose file, I will add an example
4. It would be better to run in this mode in container as docker is mainly designed to run one main process, that's why systemd container has to run in privileged mode and bind `cgroup` of the host

**Comment by jb-alvarado** [comment]
Thank you very much, @0DUDDU! 

I hope soon comes a second alpha or first beta from bootstrap 5.3, then I will merge everything to master.

**Comment by jb-alvarado** [comment]
I created a pull request on your repo, because of a wrong dependencies.

**Pull request merged**
